### ISSUE TITLE
Feature request: common factor attack with a collection of keys

### ISSUE THREAD

**Issue by fansanelli** [RsaCtfTool/RsaCtfTool#402]
Hello,

sometimes I may just want to test the security of a single key, but using a collection of keys to verify if a common factor attack is possible. A kind of "hybrid" mode:

./RsaCtfTool.py --publickey ./key.pub --private --checkagainst "*.pub"

or

./RsaCtfTool.py --publickey "*.pub" --private --target ./key.pub

what do you think?
Hope is fine to opening an Issue for such things.
Many thanks for you great work
Cheers
Francesco

**Comment by daedalus** [comment]
There is already a common factor attack between 2 o more public explonents.

**Comment by fansanelli** [comment]
Can you please clarify how? Because current mode does all the possible combinations, and it's too expensive...
For 6 keys are 21 combinations, but are 5 the ones I care.
Hope it's clear

**Comment by daedalus** [comment]
It's the cartesian product, maybe it's not the best efficient method but it's going to get all the factorizations is common factors shared.

**Comment by fansanelli** [comment]
Great news. What do you think about this request? Would you accept a PR in case you don't have time for the development?

**Comment by fansanelli** [comment]
Forgot to mention that if I have a collection of modulus (120000+) you can assume that the Cartesian product has already been done and that the test would run forever.

**Comment by daedalus** [comment]
> Great news. What do you think about this request? Would you accept a PR in case you don't have time for the development?

It will be gratefully appreciated.

**Comment by daedalus** [comment]
Btw take a look at the two different attacks under the folder multi: common_factor and common_modulus

**Comment by daedalus** [comment]
Im closing this since:

In the latest commits:

1. The attack common_factor is the one we are talking and is very efficient finding common factors across public modulus sharing them, there will be not much gain implementing the batchgcd algorithm now but it will be done in the future.

2. The attack common_modulus was renamed to common_modulus_related_message, this attack checks if two messages with two different exponents with the same public modulus gives out the original plaint text. Maybe common_modulus could be missleading, since that I decided to rename the attack to something more explicative. Currently I dont know how to make it more eficcient (maybe applying chinesse remainder theorem).
